[package]
name = "community-events"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
chrono = { version = "0.4", features = ["serde"] }
glob = "0.3"
hcl-rs = "0.12"
indexmap = "1"
serde = { version = "1", features = ["derive"] }
url = { version = "2", features = ["serde"] }
